### ISSUE TITLE
npm old code version (need help)

### ISSUE THREAD

**Issue by danibs** [dbfannin/ngx-logger#37]
Hi,
I run `npm update` and inside package.json and it update to
`"ngx-logger": "^1.1.1"`

but looking at the source, it is not sincronized with the one present on github.

**Comment by dbfannin** [comment]
@danibs, Sorry, it was in a weird state and I need to get it back to a good state before I published to npm. You should now be able to be able to pull in version 2.0.0 wish supports angular 5.

**Comment by danibs** [comment]
Ok, thanks.
The main reason of updating is the problem, already present in another Issue, with log (in the console) do not print the line number of the "real" .js file source. But looking at the (`npm`) downloaded source I still see the line `console.log.apply` instead of the current (on github) `console.log` .

Any suggestion? Are you working on that?
Thanks

**Comment by dbfannin** [comment]
It's been discussed, but no good solution has been thought of. See #21.

**Comment by AdamVig** [comment]
The version currently published on npm is now `1.1.2`, which has peer dependencies of `@angular/core@^4.3.0` and `@angular/common@^4.3.0`, which is annoying in an Angular 5 app because the peer dependency warning is logged to the console every time an npm command is run.

@dbfannin Will you publish the latest version to npm?

**Comment by dbfannin** [comment]
@AdamVig that is just the latest thing published. 2.0.0 exists and supports angular 5. We pushed a bug fix out for the angular 4 version, which is we it is the latest published version.

**Comment by AdamVig** [comment]
@dbfannin thanks for the clarification!

**Comment by dbfannin** [comment]
closing this as a non-issue
